name: brain_rivals
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  user_repository:
    path: packages/user_repository

  lottie: ^3.2.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.2
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/lottie/

