// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ8a-DUyEAfczL4jVhBp66rxfQIxG9fL0',
    appId: '1:156210365137:web:902fb260e54f094764fbf0',
    messagingSenderId: '156210365137',
    projectId: 'brain-rivals',
    authDomain: 'brain-rivals.firebaseapp.com',
    storageBucket: 'brain-rivals.firebasestorage.app',
    measurementId: 'G-QMR0R1ZB6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWPoy68AXhiUoKW0uxRkUlgjemu6oHnbk',
    appId: '1:156210365137:android:441cd09242db64ec64fbf0',
    messagingSenderId: '156210365137',
    projectId: 'brain-rivals',
    storageBucket: 'brain-rivals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6cjDsnHMylMGhVmb-7GCdgKw1rieH9VY',
    appId: '1:156210365137:ios:724e3cdd9aaddfff64fbf0',
    messagingSenderId: '156210365137',
    projectId: 'brain-rivals',
    storageBucket: 'brain-rivals.firebasestorage.app',
    iosBundleId: 'com.example.brainRivals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6cjDsnHMylMGhVmb-7GCdgKw1rieH9VY',
    appId: '1:156210365137:ios:724e3cdd9aaddfff64fbf0',
    messagingSenderId: '156210365137',
    projectId: 'brain-rivals',
    storageBucket: 'brain-rivals.firebasestorage.app',
    iosBundleId: 'com.example.brainRivals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ8a-DUyEAfczL4jVhBp66rxfQIxG9fL0',
    appId: '1:156210365137:web:859de1c98273f6e564fbf0',
    messagingSenderId: '156210365137',
    projectId: 'brain-rivals',
    authDomain: 'brain-rivals.firebaseapp.com',
    storageBucket: 'brain-rivals.firebasestorage.app',
    measurementId: 'G-7MWCWD8JMQ',
  );
}
